version: '3.8'
services:
  kener:
    image: rajnandan1/kener:latest 
    container_name: kener
    #env_file: .env #uncomment this, if you are using .env file
    environment:
      - TZ=Etc/UTC
      - NODE_ENV=production
      #- PORT=3000
      #- KENER_BASE_PATH=
      #- RESEND_API_KEY=
      #- ORIGIN=
      #- KENER_SECRET_KEY=
      #- RESEND_SENDER_EMAIL=
      #- DATABASE_URL=


      ### Most likely DO NOT need to change anything below this ###

      #- PORT=3000 Port app listens on IN CONTAINER
    ports:
      - '3000:3000/tcp'
    volumes:
      - '.:/app/database:rw'
      - '.:/app/uploads:rw'
