name: Generate README

on:
  push:
    branches:
      - main
    paths:
      - 'README.template.md'
  pull_request:
    branches:
      - main
    paths:
      - 'README.template.md'
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # Explicitly allow pushing changes

jobs:
  generate-readme:
    name: Generate README from template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch full history, including tags
          persist-credentials: false  # We'll manually authenticate

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install mustache dotenv

      - name: Download Version File
        uses: actions/download-artifact@v4.1.8
        with:
          name: version-metadata

      - name: Load Variables from File
        run: |
          while IFS='=' read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done < versions.txt

      - name: Generate README.md
        env:
          BUILD_FULL_VERSION: ${{ env.BUILD_FULL_VERSION }}  # e.g., 1.2.3
          BUILD_MAJOR_MINOR_VERSION: ${{ env.BUILD_MAJOR_MINOR_VERSION }}  # e.g., 1.2
          BUILD_MAJOR_VERSION: ${{ env.BUILD_MAJOR_VERSION }}  # e.g., 1
        run: node scripts/generate-readme.js

      - name: Commit and Push Changes
        env:
          KENER_GH_PAT_TOKEN: ${{ secrets.KENER_GH_PAT_TOKEN }}
        run: |
          git add README.md
          git commit -m "Auto-generate README.md with release versions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.KENER_GH_PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
